### ISSUE TITLE
Assemblies in NuGet package are not signed

### ISSUE THREAD

**Issue by dsosunov** [Particular/ServiceControl.Plugin.Nsb6.Heartbeat#16]
In V2.0 assemblies doesn't have strong name.

1>CSC : warning CS8002: Referenced assembly 'ServiceControl.Plugin.Nsb6.Heartbeat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by HEskandari** [comment]
@dsosunov Just to be clear, you want the assemblies to be strong named, correct? This is different than signing them with a certificate.

**Comment by dsosunov** [comment]
Yes, all our projects has strong name. If plugin don't have a strong name we cannot use it.

**Comment by HEskandari** [comment]
@dsosunov Thanks for clarifying that. I have submitted the PRs to do that. We'll coordinate a release and you should be able to update to use the strong name assemblies. This issue will be kept opened until the PRs get merged in.
